config/routes.rb
Rails.application.routes.draw do

  root "static#home"
  
  get 'auth/:provider/callback', to: 'sessions#omniauth'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show'

  get '/login', to: 'sessions#new' 
  post '/login', to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  resources :playlists
  resources :songs
  resources :users do
  resources :playlists, only: [:index, :create, :new]
end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    belongs_to :user
    has_many :playlists_songs, dependent: :destroy
    has_many :songs, through: :playlists_songs
    validates :name, presence: true
    validates :name, uniqueness: { scope: :user_id}
    accepts_nested_attributes_for :playlists_songs

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    before_action :redirect_if_not_logged_in
    layout "playlist"

    def index
        if params[:user_id] && @user = User.find(params[:user_id])
            @playlists = @user.playlists
        else
            @playlists = Playlist.all
        end
    end

    def new
        if params[:user_id] && @user = User.find(params[:user_id])
            @playlist = Playlist.new(user_id: params[:user_id])
        else
            @playlist = Playlist.new
        end
    end

    def create
        @user = current_user
        @playlist = Playlist.create(playlist_params)
        if @playlist.valid?
            redirect_to user_playlists_path(@user)
        else
            render :new
        end
    end
    
    def show
        @playlist = find_playlist
        render :layout => "application"
    end

    def edit
        @user = current_user
        @playlist = find_playlist
    end

    def update 
        @user = current_user
        @playlist = find_playlist
        if @playlist.update(playlist_params)
            redirect_to user_playlists_path(@user)
        else 
            render :edit
        end
    end

    def destroy
        @user = current_user
        @playlist = find_playlist
        @playlist.destroy
        redirect_to user_playlists_path(@user)
    end

    private

    def find_playlist
        @playlist = Playlist.find_by_id(params[:id])
    end

    def playlist_params
        params.require(:playlist).permit(:name, :favorite, :user_id, playlists_songs_attributes: [:playlist_id, :song_id, :rating, :id])
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper

    def show_rating(song_id, playlist_id)
        ps = PlaylistsSong.find_by(song_id: song_id, playlist_id: playlist_id)
        if ps.rating == nil
            content_tag(:h3, "Rating: 0/5")
        else
            content_tag(:h3, "Rating: #{ps.rating}/5 ")
        end
    end

    def show_playlists(playlists)
        if playlists.length == 0
            content_tag(:h3, "You have no playlists, please create one!!")
        else
            render partial: "playlist"
        end
    end

    def show_all_songs(playlist)
        if playlist.songs.length == 0
            content_tag(:h3, "This playlist has no tracks, add some!!")
        else
            playlist.songs.map do |song|
               show_song(song, playlist)
            end.join.html_safe
        end
    end

    def show_song(song, playlist)
        tag.div class: "song-contrainer" do 
            concat render partial: "songs/song", locals: {song:song}
            concat show_rating(song.id, playlist.id)
            concat render partial: "delete", locals: {song: song, playlist: playlist}
        end
    end
end

app/views/playlists/_delete.html.erb
<%= form_for(:song, url: song_path(song), :html => { method: "delete" }) do |f| %>
    <%= f.hidden_field :id, :value => playlist.id %>
<%= f.submit "Remove Track" %>
<% end %>
<br><br>

app/views/playlists/_form.html.erb
<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :favorite? %><br>
<%= f.select :favorite, options_for_select([["No", false], ["Yes", true]]) %><br><br>
        
<%= f.hidden_field :user_id, :value => @user.id %>

app/views/playlists/_playlist.html.erb
<% @playlists.each do |playlist| %>
     <h4><%= playlist.name %></h4>
    <h4>Tracks: <%= playlist.songs.length %></h4>
    <h4><%= link_to "View Playlist", playlist_path(playlist) %></h4>
    <%= link_to "Edit Playlist", edit_playlist_path(playlist) %>
    <%= button_to "Delete Playlist", playlist, method: :delete %>
    <br><br>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit your Playlist</h1>

<%= conditional_errors(@playlist) %>



    
<div class="container">
    <%= form_with(model: @playlist) do |f| %>
        
        <%= render partial: "form", locals: {f: f} %>

        <% @playlist.songs.each do |song| %>
            
            <%= render song %>
            <%= f.fields_for :playlists_songs, a = PlaylistsSong.find_by(song_id: song.id, playlist_id: @playlist.id)  do |song_field| %>
                <h3><%= song_field.label :rating %><h3>
                <%= song_field.select :rating, options_for_select([["0", "0"],["1", "1"],["2", "2"],["3", "3"],["4", "4"],["5", "5"]], :selected => a.rating) %>
            <% end %><br><br>

        <% end %>
            
        <%= f.submit %>
    <% end %>
</div>

app/views/playlists/index.html.erb
<h1>Your Playlists</h1>
<div class=container>
    <%= show_playlists(@playlists) %>
    <br><br>
    <%= link_to "Create a Playlist", new_user_playlist_path, class: 'button' %>
</div>

app/views/playlists/new.html.erb
<h1>Create a Playlist</h1>

<%= conditional_errors(@playlist) %>

<%= form_with(model: @playlist) do |f| %>      
    <%= render partial: "form", locals: {f: f} %>
    <%= f.submit %>
<% end %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>
 <%= link_to "Edit Playlist", edit_playlist_path(@playlist) %><br>
<div class="container">
 <%= show_all_songs(@playlist) %>
</div>