config/routes.rb
Rails.application.routes.draw do

  root "static#home"
  
  get 'auth/:provider/callback', to: 'sessions#omniauth'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show'

  get '/login', to: 'sessions#new' 
  post '/login', to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  resources :playlists
  resources :songs
  resources :users do
  resources :playlists, only: [:index, :create, :new]
end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!doctype html>
  <html lang="en">
    <head>
    
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    
    </head>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <%= logo %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <% if logged_in? %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= user_path(current_user) %>">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= user_playlists_path(current_user) %>">Playlists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= songs_path %>">Songs</a>
                        </li>
                    <% end %>
                    <% if logged_in? %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= logout_path %>">Log Out</a>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= login_path %>">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= signup_path %>">Sign Up</a>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>

    <body class="p-3 mb-2 bg-dark text-white">
     
      
        <%= yield %>
      
  

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
  </html>

app/views/layouts/playlist.html.erb
<!doctype html>
  <html lang="en">
    <head>
    
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    
    </head>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <%= logo %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <% if logged_in? %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= user_path(current_user) %>">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= songs_path %>">Songs</a>
                        </li>
                    <% end %>
                    <% if logged_in? %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= logout_path %>">Log Out</a>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= login_path %>">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= signup_path %>">Sign Up</a>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>

    <% flash.keys.each do |type| %>
    <div data-alert class="flash <%= type %> alert-box radius">
      <%= flash[type] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
    <body class="p-3 mb-2 bg-dark text-white">
     
      
        <%= yield %>
      
  

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
  </html>

app/views/layouts/song.html.erb
<!doctype html>
  <html lang="en">
    <head>
    
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    
    </head>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <%= logo %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <% if logged_in? %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= user_path(current_user) %>">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= user_playlists_path(@user) %>">Playlists</a>
                        </li>
                    <% end %>
                    <% if logged_in? %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= logout_path %>">Log Out</a>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= login_path %>">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= signup_path %>">Sign Up</a>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>

    <% flash.keys.each do |type| %>
    <div data-alert class="flash <%= type %> alert-box radius">
      <%= flash[type] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
    <body class="p-3 mb-2 bg-dark text-white">
     
      
        <%= yield %>
      
  

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
  </html>

app/views/layouts/user.html.erb
<!doctype html>
  <html lang="en">
    <head>
    
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    
    </head>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <%= logo %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <% if logged_in? %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= user_playlists_path(@user) %>">Playlists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= songs_path %>">Songs</a>
                        </li>
                    <% end %>
                    <% if logged_in? %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= logout_path %>">Log Out</a>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= login_path %>">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= signup_path %>">Sign Up</a>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
    <body class="p-3 mb-2 bg-dark text-white">
     
      
        <%= yield %>
      
  

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
  </html>